export default Object.freeze({
  INSERTED_SUCCESSFULLY: 'Data inserted successfully',
  SUCCESSFULLY_FETCHED: 'fetched data Successfully',
  DELETE_SUCCESSFUL: 'Deleted successfully',
  PRINT_TO_CONSOLE: 'LOGGED IN CONSOLE',
  DATA_UPDATED: 'Data updated successfully',
  FOUND: 'Found data successFully',
  UPLOAD_SUCCESS: 'File uploaded successfully',
  NO_ROUTE: 'No route found',
  DUPLICATE_EMAIL: 'Duplicate email found,please login',
  UPLOAD_FAIL: 'Failed to upload',
  NO_REQUEST_BODY: 'No request body',
  DUPLICATE_ENTRIES: 'Duplicate entries has been found',
  DUPLICATE_RECORD: 'Duplicate record has been found',
  NO_RECORD_FOUND: 'No record found',
  INVALID_INPUT: 'Invalid,please provide a Valid input',
  CANNOT_FETCH: 'Cannot fetch Data',
  NOT_INSERTED: 'Data not inserted properly',
  UPDATE_FAIL: 'failed to update data',
});
